### ISSUE TITLE
Add awesome-cryptography

### ISSUE THREAD

**Issue by sobolevn** [sweis/crypto-might-not-suck#15]
A curated list of cryptography resources and links.
https://github.com/sobolevn/awesome-cryptography

**Comment by sweis** [comment]
Thank you. Some of the content on Awesome Cryptography is pretty out of date. For example, it mentions Blowfish, but not modern ciphers like Chacha20. It also only talks about RSA, but no modern ECC.

**Comment by sobolevn** [comment]
Thank you for your feedback! I would highly appreciate your contributions if you have something to add to `awesome-cryptography`.
