### ISSUE TITLE
Add 2key-ratchet

### ISSUE THREAD

**Issue by rmhrisk** [sweis/crypto-might-not-suck#16]
I have created a JS implementation of a double ratchet protocol based on WebCrypto.

https://github.com/PeculiarVentures/2key-ratchet

Would be appreciated if it could be included.

**Comment by sweis** [comment]
Thanks for all these issues suggesting your JS projects. I am pretty conservative adding JS libraries and am going to wait and see how adopted or battle tested these are.

I do have some experimental stuff on the list, but it tends to be more esoteric crypto like Charm or Relic. 

There's a JS crypto list here you may want to look at: https://gist.github.com/jo/8619441
