### ISSUE TITLE
Nitrokey

### ISSUE THREAD

**Issue by reezer** [sweis/crypto-might-not-suck#9]
Is hardware also something for the list?

There would be Nitrokey and they are very open, also released information of an audit. They are backed by/part of Open Technology Fund, Open Hardware, Mozilla, FOSS Asia and the German Privacy Foundation, among others.

At least to me it would some like the perfect candidate as it integrates with other tools mentioned here. Of course I wouldn't add closed hardware.

https://www.nitrokey.com/

**Comment by sweis** [comment]
Nitrokey doesn't support modern crypto and the code doesn't appear to have had much review. I'm not going to add it at this time.

**Comment by reezer** [comment]
Just wanted to mention a few things:

They actually had a complete third party audit of both hardware and firmware, which is more than various of other projects in the list:
- https://www.nitrokey.com/sites/default/files/NitrokeyFirmwareSecurityAuditReport05-2015.pdf
- https://www.nitrokey.com/sites/default/files/NitrokeyHardwareSecurityAuditReport08-2015.pdf

Also they support:
- ECC
- One Time Passwords
- Hidden Volumes
- many projects mentioned in the list (GPG, OpenSSL, OpenSSH, etc.) and others

But I agree with you, if you mean review in the sense of big mass of users. Also it would certainly be an experimental project. But then again it would fit with the other misc projects, wouldn't it?
